CREATE VIEW `pl_away_picks_vw` AS select `pl_picks`.`season` AS `season`,`pl_picks`.`week` AS `week`,`pl_picks`.`home_team` AS `home_team`,`pl_picks`.`away_team` AS `away_team`,count(0) AS `picks` from `pl_picks` where (`pl_picks`.`pick` = `pl_picks`.`away_team`) group by `pl_picks`.`week`,`pl_picks`.`season`,`pl_picks`.`home_team`,`pl_picks`.`away_team`;

CREATE VIEW `pl_home_picks_vw` AS select `pl_picks`.`season` AS `season`,`pl_picks`.`week` AS `week`,`pl_picks`.`home_team` AS `home_team`,`pl_picks`.`away_team` AS `away_team`,count(0) AS `picks` from `pl_picks` where (`pl_picks`.`pick` = `pl_picks`.`home_team`) group by `pl_picks`.`week`,`pl_picks`.`season`,`pl_picks`.`home_team`,`pl_picks`.`away_team`;

CREATE VIEW `pl_user_picks_vw` AS select `u`.`user_name` AS `user_name`,`u`.`display_rank` AS `display_rank`,`g`.`season` AS `season`,`g`.`week` AS `week`,`g`.`start_time` AS `start_time`,`g`.`home_team` AS `home_team`,`g`.`away_team` AS `away_team`,`g`.`home_score` AS `home_score`,`g`.`away_score` AS `away_score`,`g`.`spread` AS `spread`,`p`.`pick` AS `pick`,(case when isnull(`p`.`push`) then 0 else `p`.`push` end) AS `push` from ((`pl_users` `u` join `pl_games` `g` on((`u`.`season` = `g`.`season`))) left join `pl_picks` `p` on(((`u`.`user_name` = `p`.`user_name`) and (`u`.`season` = `p`.`season`) and (`g`.`season` = `p`.`season`) and (`g`.`week` = `p`.`week`) and (`g`.`home_team` = `p`.`home_team`) and (`g`.`away_team` = `p`.`away_team`))));

CREATE VIEW `pl_majority_vw` AS select `g`.`season` AS `season`,`g`.`week` AS `week`,`g`.`home_team` AS `home_team`,`g`.`away_team` AS `away_team`,(case when (`h`.`picks` > `a`.`picks`) then `g`.`home_team` else (case when (`a`.`picks` > `h`.`picks`) then `g`.`away_team` else NULL end) end) AS `majority`,(case when (`h`.`picks` > `a`.`picks`) then `h`.`picks` else (case when (`a`.`picks` > `h`.`picks`) then `a`.`picks` else NULL end) end) AS `maj_picks`,(case when (`h`.`picks` > `a`.`picks`) then `a`.`picks` else (case when (`a`.`picks` > `h`.`picks`) then `h`.`picks` else NULL end) end) AS `min_picks`,(case when (isnull(`g`.`home_score`) or isnull(`g`.`away_score`)) then NULL else (case when ((`g`.`home_score` + `g`.`spread`) > `g`.`away_score`) then `g`.`home_team` else (case when ((`g`.`home_score` + `g`.`spread`) < `g`.`away_score`) then `g`.`away_team` else _latin1'push' end) end) end) AS `winner` from ((`pl_games` `g` join `pl_home_picks_vw` `h`) join `pl_away_picks_vw` `a`) where ((`g`.`season` = `h`.`season`) and (`g`.`season` = `a`.`season`) and (`g`.`week` = `h`.`week`) and (`g`.`week` = `a`.`week`) and (`g`.`home_team` = `h`.`home_team`) and (`g`.`home_team` = `a`.`home_team`) and (`g`.`away_team` = `h`.`away_team`) and (`g`.`away_team` = `a`.`away_team`));

CREATE VIEW `pl_record_vw` AS select `pl_user_picks_vw`.`user_name` AS `user_name`,`pl_user_picks_vw`.`display_rank` AS `display_rank`,`pl_user_picks_vw`.`season` AS `season`,`pl_user_picks_vw`.`week` AS `week`,sum((case when ((`pl_user_picks_vw`.`push` = 0) and (`pl_user_picks_vw`.`home_score` is not null) and (`pl_user_picks_vw`.`away_score` is not null) and (((`pl_user_picks_vw`.`pick` = `pl_user_picks_vw`.`home_team`) and ((`pl_user_picks_vw`.`home_score` + `pl_user_picks_vw`.`spread`) > `pl_user_picks_vw`.`away_score`)) or ((`pl_user_picks_vw`.`pick` = `pl_user_picks_vw`.`away_team`) and ((`pl_user_picks_vw`.`home_score` + `pl_user_picks_vw`.`spread`) < `pl_user_picks_vw`.`away_score`)))) then 1 else 0 end)) AS `wins`,sum((case when ((`pl_user_picks_vw`.`push` = 0) and (`pl_user_picks_vw`.`home_score` is not null) and (`pl_user_picks_vw`.`away_score` is not null) and (((`pl_user_picks_vw`.`pick` = `pl_user_picks_vw`.`home_team`) and ((`pl_user_picks_vw`.`home_score` + `pl_user_picks_vw`.`spread`) < `pl_user_picks_vw`.`away_score`)) or ((`pl_user_picks_vw`.`pick` = `pl_user_picks_vw`.`away_team`) and ((`pl_user_picks_vw`.`home_score` + `pl_user_picks_vw`.`spread`) > `pl_user_picks_vw`.`away_score`)) or isnull(`pl_user_picks_vw`.`pick`))) then 1 else 0 end)) AS `losses` from `pl_user_picks_vw` group by `pl_user_picks_vw`.`user_name`,`pl_user_picks_vw`.`week`,`pl_user_picks_vw`.`season`;

CREATE VIEW `pl_winners_vw` AS select `pl_games`.`home_team` AS `home_team`,`pl_games`.`away_team` AS `away_team`,`pl_games`.`season` AS `season`,`pl_games`.`week` AS `week`,`pl_games`.`start_time` AS `start_time`,`pl_games`.`home_score` AS `home_score`,`pl_games`.`away_score` AS `away_score`,`pl_games`.`spread` AS `spread`,(case when (isnull(`pl_games`.`home_score`) or isnull(`pl_games`.`away_score`) or isnull(`pl_games`.`spread`)) then NULL when ((`pl_games`.`home_score` + `pl_games`.`spread`) = `pl_games`.`away_score`) then _latin1'push' when ((`pl_games`.`home_score` + `pl_games`.`spread`) > `pl_games`.`away_score`) then `pl_games`.`home_team` else `pl_games`.`away_team` end) AS `winner` from `pl_games`;
