DELETE FROM pl_teams;
INSERT INTO `pl_teams` VALUES
	('ARI','Arizona','Cardinals'),
	('ATL','Atlanta','Falcons'),
	('BAL','Baltimore','Ravens'),
	('BUF','Buffalo','Bills'),
	('CAR','Carolina','Panthers'),
	('CHI','Chicago','Bears'),
	('CIN','Cincinnati','Bengals'),
	('CLE','Cleveland','Browns'),
	('DAL','Dallas','Cowboys'),
	('DEN','Denver','Broncos'),
	('DET','Detroit','Lions'),
	('GB','Green Bay','Packers'),
	('HOU','Houston','Texans'),
	('IND','Indianapolis','Colts'),
	('JAX','Jacksonville','Jaguars'),
	('KC','Kansas City','Chiefs'),
	('LA','Los Angeles','Rams'),
	('LAC','Los Angeles','Chargers'),
	('LAR','Los Angeles','Rams'),
	('MIA','Miami','Dolphins'),
	('MIN','Minnesota','Vikings'),
	('NE','New England','Patriots'),
	('NO','New Orleans','Saints'),
	('NYG','New York','Giants'),
	('NYJ','New York','Jets'),
	('OAK','Oakland','Raiders'),
	('PHI','Philadelphia','Eagles'),
	('PIT','Pittsburgh','Steelers'),
	('SD','San Diego','Chargers'),
	('SF','San Francisco','49ers'),
	('SEA','Seattle','Seahawks'),
	('STL','St. Louis','Rams'),
	('TB','Tampa Bay','Buccaneers'),
	('TEN','Tennessee','Titans'),
	('WAS','Washington','Redskins')
;
